name: Test CI/CD pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no newalexadmin@176.123.164.14 '
          cd /home/newalexadmin/ITG02_FlowerDelivery_Master &&
          git stash &&
          git pull &&
          sudo systemctl restart gunicorn &&
          sudo systemctl restart nginx &&
          git stash pop'
        rm private_key
